name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: 'NPM install'
      run: npm install

    - name: 'Coding Convention Checks - File names'
      run: npx file-name-linter .file-name-linter.json

    - name: 'Azure Policy JSON Schema Checks'
      run: npx ajv validate --format=full --all-errors --errors=no --extend-refs=fail -s vendor/schema-azure-policydefinition-2019-09-01.json -r "vendor/referenced/*.json" -d "policies/*-rule.json"

    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Format
      run: terraform fmt -check -diff

    - name: Terraform Plan
      run: terraform plan

      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
